#!/usr/bin/env python3
"""Promove apenas streams com forte evidência de origem oficial e testa HLS."""
from __future__ import annotations
import csv, re, socket
from pathlib import Path
from urllib.parse import urlparse
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
OUT = ROOT / "output"
STREAMS = DATA / "streams.csv"
CANDIDATES = OUT / "iptv-org-candidatos.csv"
REPORT = OUT / "streams-diagnostico.csv"

# Domínios institucionais que podem aparecer como CDN/subdomínio oficial.
OFFICIAL_SUFFIXES = {
    "camara.gov.br", "ebc.com.br", "gov.br", "senado.leg.br", "tvcultura.com.br",
    "al.rs.gov.br", "al.sp.gov.br", "al.pr.gov.br", "al.sc.gov.br", "al.rn.gov.br",
}
FORBIDDEN = ("xtream", "get.php", "player_api", "username=", "password=", "token=")


def clean(v): return (v or "").strip()

def host_ok(host, site):
    host = host.lower().split(":",1)[0]
    if any(host == d or host.endswith("." + d) for d in OFFICIAL_SUFFIXES):
        return True
    sm = re.search(r"https?://([^/]+)", clean(site), re.I)
    if sm:
        dom = sm.group(1).lower().split(":",1)[0].removeprefix("www.")
        if host == dom or host.endswith("." + dom):
            return True
    return False


def test_stream(url):
    try:
        req = Request(url, headers={"User-Agent":"brasil-tv-m3u/2.0", "Accept":"application/vnd.apple.mpegurl,application/x-mpegURL,*/*"})
        with urlopen(req, timeout=12) as r:
            code = getattr(r, "status", 200)
            data = r.read(8192)
            ctype = (r.headers.get("Content-Type") or "").lower()
        text = data.decode("utf-8", "ignore")
        ok = code in (200, 206) and ("#EXTM3U" in text or "mpegurl" in ctype or "vnd.apple.mpegurl" in ctype)
        return ok, f"HTTP {code}; {ctype or 'sem-content-type'}"
    except Exception as e:
        return False, f"{type(e).__name__}: {e}"


def read_rows(path):
    if not path.exists(): return []
    with open(path, encoding="utf-8-sig", newline="") as f: return list(csv.DictReader(f))


def main():
    channels = {r["id"]: r for r in read_rows(DATA / "emissoras.csv") if clean(r.get("id"))}
    existing = read_rows(STREAMS)
    kept = {}
    for r in existing:
        if clean(r.get("emissora_id")) and clean(r.get("url")):
            kept[(r["emissora_id"], r["url"])] = r

    report = []
    # Candidates generated by IPTV-org are only accepted when their URL host has
    # institutional evidence (official domain/CDN) and the match is high confidence.
    for r in read_rows(CANDIDATES):
        c = channels.get(clean(r.get("emissora_id")))
        if not c or int(r.get("score") or 0) < 88:
            continue
        url = clean(r.get("url"))
        if not url.lower().startswith(("http://", "https://")) or any(x in url.lower() for x in FORBIDDEN):
            continue
        host = urlparse(url).netloc.lower()
        if not host_ok(host, c.get("Site oficial", "")):
            continue
        ok, detail = test_stream(url)
        report.append([c["id"], c["Emissora"], c["Estado"], c["Cidade"], r["score"], host, url, "APROVADO" if ok else "REJEITADO", detail])
        if ok:
            kept[(c["id"], url)] = {
                "emissora_id": c["id"], "url": url,
                "origem": "official_external_cdn", "status": "validated",
                "observacao": f"Descoberto via IPTV-org; domínio institucional validado ({host})."
            }

    # Revalidate existing official streams; inactive streams are removed from M3U
    # but remain visible in the diagnostic report.
    final = []
    for key, r in sorted(kept.items()):
        c = channels.get(clean(r.get("emissora_id")))
        if not c: continue
        url = clean(r.get("url"))
        if any(x in url.lower() for x in FORBIDDEN): continue
        if clean(r.get("origem")) in {"official", "government", "university", "official_external_cdn"}:
            ok, detail = test_stream(url)
            report.append([c["id"], c["Emissora"], c["Estado"], c["Cidade"], "existente", urlparse(url).netloc.lower(), url, "ATIVO" if ok else "INATIVO", detail])
            if ok:
                r["status"] = "validated"
                final.append(r)

    # De-duplicate globally by URL. A single HLS endpoint must not appear
    # more than once in streams.csv, even if discovery associated it with
    # multiple records. Keep the first deterministic association.
    final.sort(key=lambda r: (clean(r.get("url")).lower(), clean(r.get("emissora_id"))))
    final_map = {}
    for r in final:
        u = clean(r.get("url"))
        if not u or u in final_map:
            continue
        final_map[u] = r
    with open(STREAMS, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["emissora_id","url","origem","status","observacao"])
        w.writeheader(); w.writerows(final_map.values())
    with open(REPORT, "w", encoding="utf-8", newline="") as f:
        w = csv.writer(f); w.writerow(["emissora_id","emissora","estado","cidade","score","host","url","resultado","detalhe"]); w.writerows(report)
    print(f"Streams ativos/validados: {len(final_map)}")
    print(f"Diagnóstico: {REPORT}")

if __name__ == "__main__": main()
